# Built with Jekyll 3.6.0

# Setup
title:               Web Mapping Notes
tagline:             'Guide, materials & resources'
description:         'An archive to teach Web Mapping & Analysis.'
url:                 'https://darribas.org'
baseurl:             '/wmn'
repository:          'https://github.com/darribas/wmn'

# About/contact
author:
  name:              Dani Arribas-Bel
  twitter:           darribas
  url:               https://darribas.org
  email:             <code>D.Arribas-Bel [at] liverpool.ac.uk</code>
  title:             Senior Lecturer in Geographic Data Science
  add1:              Office 508, Roxby Building
  add2:              University of Liverpool
  add3:              Liverpool L69 3BX, United Kingdom

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
#permalink: pretty
permalink: /:title

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

# Theme
# (Used for local or custom-server deployments)
# Uncomment the `theme` line if using the Ed. theme gem on your own computer or server.
# See https://jekyllrb.com/docs/themes/
# theme: "ed."

# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
#remote_theme: minicomp/ed


# Syllabus

blocks:
    b1:
        name: "Introduction"
        lecture: "Introduction to the module"
        lab: "Getting up to speed for web mapping"
    b2:
        name: "The context of Web Maps"
        lecture: "The Web's architecture and Economy"
        lab: "Powerful examples"
    b3:
        name: "Data Backends I"
        lecture: "Data architechtures & formats"
        lab: "Creating, manipulating, and integrating web geospatial data"
    b4:
        name: "Data Backends II"
        lecture: "APIs"
        lab: "Acquiring data from the web"
    b5:
        name: "Data Backends III"
        lecture: "Building and deploying (web) platforms + Assignment details"
        lab: "Assignment I clinic"
    b6:
        name: "Frontend Topics I"
        lecture: "Good (Web) Maps"
        lab: "CARTO sandbox"
    b7:
        name: "Frontend Topics II"
        lecture: "Map design"
        lab: "Designing maps with Mapbox Studio and CARTO"
    b8:
        name: "Frontend Topics III"
        lecture: "Interactivity"
        lab: "Designing for interactivity"
    b9:
        name: "Dashboards"
        lecture: "Dashboards: bringing analysis to the web"
        lab: "Building Dashboards"
    b10:
        name: "Technology gallery"
        lecture: "Technology gallery"
        lab: "Assignment II clinic"
assessment:
    a1:
        title: "Combining (geo-)data in an interactive map"
    a2:
        title: "A dashboard of IMD"

